name: 'Program Improvements'
description: 'Improvements for the Python script'
title: "Program improvement: (Short, descriptive title)"
labels: ["enhancement"]
assignees:
  - terminalcommandnewsletter
body:
  - type: checkboxes
    attributes:
      label: 'Is there an existing issue for this?'
      description: 'Please search to see if an issue already exists for the feature not being covered in the repo.'
      options:
      - label: 'I have searched the existing issues'
        required: true
  - type: textarea
    id: feature-info
    attributes:
      label: 'What is the improvement about?'
      placeholder: 'e.g. Add [...]'
    validations:
      required: true
  - type: checkboxes
    id: contributing-md
    attributes:
      label: 'CONTRIBUTING.md'
      description: 'By submitting this issue, I agree that I have read the `CONTRIBUTING.md` of this repo and this issue adheres to those guidelines.'
      options:
        - label: I have read the `CONTRIBUTING.md`
          required: true